name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
          cache: npm

      - name: Linter
        run: npm run lint

